### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Leo030110** [Divine-Journey-2/Divine-Journey-2#1016]
### Describe the feature

Whatever modpack dev is reading this, i'd like to please have DJ2 on modrinth because of all the controversies with curseforge. If you don't know what is happening or the benefits of Modrinth, watch this video created by Purplers: https://www.youtube.com/watch?v=Vhdwz5apiQQ

Now, you may be wondering: how do we port DJ2 to modrinth? Well, the answer is simple, and is even contained within Modrinth documentation, so please read that at https://docs.modrinth.com/docs/getting-started/.

That is all i want to talk about here.

### Reasons why this should be added

The video by Purplers on the first part.

### Your Divine Journey 2 Discord Username

theleonardofad

**Comment by WaitingIdly** [comment]
in order to use a given mod in a Modrinth modpack, one of two things must be true:
1. the mod is downloadable on Modrinth or via github releases (see [Modrith's documentation](https://docs.modrinth.com/docs/modpacks/format_definition/#downloads))
2. the mod is open source or otherwise gives explicit permission to be redistributed

if neither of these two things are met - which is true for a number of mods in DJ2 - the mod cannot be used as part of a Modrinth pack. given that the status on some of those mods is "abandoned", this state isnt going to change anytime soon, if ever.
