### ISSUE TITLE
AE2 with Mekanism

### ISSUE THREAD

**Issue by Xeorx1** [Divine-Journey-2/Divine-Journey-2#1026]
### Modpack version

2.19.2

### Description

Hello,

Is the bug known that Mekanism does not work properly? 
For example, when I want to build a Basic Infusing Factory from Mekanism via the ME with Autocrafting, it says that the pre-machine is not saved as a recipe, here the Metallurgic Infuser. But I can build the Metallurgic Infuser individually. 

### Steps to reproduce

1. Craft a "Basic Infusing Factory" with autocraft.

### Expected behavior

idk

### Additional context

https://i.imgur.com/5wDT9gj.png
https://i.imgur.com/BsQvgxg.png

### Your Divine Journey 2 Discord Username

cracks_

**Comment by noel357** [comment]
Yes it's a known bug with AE and NBT, to fix it you have to remake the Patterns and request the first machine and put it into the Pattern of the second manually with drag and drop without putting the machine into your inv, only Terminal -> Pattern -> back into your ME.

**Comment by WaitingIdly** [comment]
because of how AE2 works, when you encode a pattern with an item containing specific NBT, it will look for an item with that specific NBT. since the item you have doesnt match the NBT its looking for, it will not match. JEI does not auto-fill the NBT data of some recipes correctly, requiring those items will need to be manually replaced for the pattern to function properly.
this is not a bug.
