### ISSUE TITLE
Crashes upon starting due to Serialization is Bad loading remote config file

### ISSUE THREAD

**Issue by mainnivia** [Divine-Journey-2/Divine-Journey-2#1133]
### Modpack version

2.20.0

### Java version

Build 1.8.0_371-b11

### RAM Allocated

8gigs

### Description

logs states that it crashes cuz "failed to load remote config", already tried to reinstall

### When did the crash happen?

during load up

### Steps to reproduce

start the modpack

### Minecraft crash report

[latest.log](https://github.com/Divine-Journey-2/Divine-Journey-2/files/14627450/latest.log)

**Comment by WaitingIdly** [comment]
this error is caused due to:
1. CurseForge, ATLauncher, and a few others ship a custom and outdated version of Java, typically 1.8.0_51.
2. Serialization Is Bad, as part of its patching process, checks for updates from `raw.githubusercontent.com`.
3. The certification for `raw.githubusercontent.com` was changed just recently, and this old version of Java doesn't have the proper certificates to access it.


fixes, and any of these should work:
1. Update Java. You should do this regardless, and if your launcher does not allow it, you should switch launchers.
2. in `config/serializationisbad.json`, change `remoteConfigUrl` to `https://serializationisbad.dogboy.io/serializationisbad.json`. 
3. Update Serialization is Bad (should work with servers) https://legacy.curseforge.com/minecraft/mc-mods/serializationisbad/files.
