### ISSUE TITLE
AE2 meteors not spawning

### ISSUE THREAD

**Issue by mattba10** [Divine-Journey-2/Divine-Journey-2#1150]
### Modpack version

2.20.1

### Description

Currently playing on a server. AE2 meteors do not spawn in the Atum (compass worked but no meteor spawned). Server owner fix was to make them spawn in the overworld. This worked but now custom presses are not spawning in them.

### Steps to reproduce

N/A

### Expected behavior

Meteors should spawn in atum and should have custom presses

### Additional context

N/A

### Your Divine Journey 2 Discord Username

Mattba20

**Comment by WaitingIdly** [comment]
custom ae2 presses will not spawn because you are not using the custom meteors. as to why the meteors are not generating:
1. are you absolutely sure it is that the meteors are not generating.
2. it may be that there are no Recurrent Complex structures generating. make sure the server owner has not disabled them, reduced their generation rate.
3. it may be that the structure file is not present on the server. ensure that the files inside https://github.com/Divine-Journey-2/Divine-Journey-2/tree/main/overrides/structures/active match

**Comment by mattba10** [comment]
Hi Waiting - thanks for your response.

1. Yes I am certain - I have been to over 4 places with spinning compass and mined out the chunks. I can also phase through the ground with roots and could not find the meteors/chests.
2. Thank you - I will check this.
3. Thank you - will check this. Will this likely fix the fact that strongholds dont spawn portals. Rather of interest as the overworld is all pre-generated.

**Comment by mattba10** [comment]
2. Using /#structures tweak all numbers are 1.0 - I assume this means that this is default.
3. "Checked the structures folder and the ones relevant to AE2 do exist under active"

Are you able to suggest anything else - as it seems we have done all the initial steps you suggested
