### ISSUE TITLE
Water from the fluid tank doesn't get consumed in a treated leather craft.

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/Divine-Journey-2#311]
**Modpack version:**
2.3.1

**Description:**
When you put a fluid tank(thermal one, haven't tested with others) filled with water instead of a water bucket in a treated leather crafting recipe, water doesn't get consumed.

**Steps to reproduce:**
^

**Expected behavior:**
If this in unintentional, remove an ability to craft with a fluid tank or just let it consume the 1000mb per craft if this is possible.

**Comment by Atricos** [comment]
This is only an issue in the Crafting Terminal, and it's a known bug. I removed the Energized Certus and Energized Osmium Tank recipes because of this, but duplicating water isn't that big of a deal.

CraftTweaker has a hard time differentiating between crafting inventory types, so there is a probably a fix for this, but it's not a simple one. Last time I spent 4 hours trying to figure out how to make the Terminal use up the liquid or at least trying to remove the recipe from (only) the AE2 terminal, and other potential crafters that are affected (e.g. Mekanism Formulaic Assemblicator, RFTools Crafter, Crafting Table on a Stick, Botania Assembly Halo, etc.); but no luck.
