### ISSUE TITLE
Thoughts up to Chapter 27. Lightningcraft, Galacticraft plates, Alchemistry

### ISSUE THREAD

**Issue by jehlp** [Divine-Journey-2/Divine-Journey-2#460]
**Modpack version:**
2.6.0 (irrelevant)

I have been urged again and again to make all the suggestions I have for this pack on GitHub, and I have finally caved and I hope you will take at least some of these seriously, because as of current, we're some of the few people that have made it to the late game of the pack. The pack has been a ton of fun, we've sunk many, many hours already and there are still quite a few hours left. As ambitious as DJ2 is, I was frankly very very impressed in terms of balance, chapters 15-18 were some of the most fun I've had in modded Minecraft. However towards the tail end of chapter 22 or so, it became very clear that there is a lot of imbalance in the pack due to lack of testing. Hell, one of your two mods (the only one that actually is active in the chat, generally very helpful) genuinely thought you only needed ~20 rainbow tablets to beat the pack. Lol

(not to mention until a patch or two ago, like most of the important t4 seeds were uncraftable. Also even currently the superium infusion crystal is not craftable. but thats aside the point. im just showing that no one really tested this, as there are very important items for progression that are impossible to make)

-------------------

**FIRST: LIGHTNINGCRAFT**

Lets get some ratios written down.

1 mystical iron + 4 cyanite -> 1 blutonium
1 blutonium -> 2 resonating gems
1 resonating gem -> 5 galactic ingot.

So 1 mystical iron per 10 galactic ingots.

Considering that you need tens (maybe hundreds) of thousands of galactic ingots for all the plates, this means you're going to need a ridiculous amount of mystical iron ingots.

Each mystical iron ingot takes 1/3 of a divine underpower, each of which takes 4 skyfather dust, skyfather comes from electricium... and all of this is done in the lightning infusion table. Each craft in that table, even when upgraded, is 15 seconds. So it comes to the point where you are quite literally waiting WEEKS of 100% uptime to generate all the skyfather/divine underpowder you need. Solution? **Electricium and Skyfather seeds.** 

(mystic ingots are justified. no seeds needed there, I like the challenge of the ichor)

It was just odd to me that the only custom seed in the pack is the Solar seed, which is completely useless when you can just quarry venus once and you have more than enough for the rest of your playthrough, while lightningcraft stuff you just have to WAIT on.

-------------------

**SECOND: GALACTICRAFT PLATES**

These take... forever. The ultimate compressor is actually inefficient to create, as (we tested) the 12 advanced compressors run in parallel work ~5.5x faster than the ultimate compressor itself. Just a ton of unfun waiting, again. In my opinion, the compressor should be similar to the advanced inscriber in terms of speed.  So basically, **BUFF THE ULTIMATE COMPRESSOR A LOT**

-------------------

**THIRD MOST IMPORTANTLY PLEASE CHANGE: ALCHEMISTRY**

Alchemistry was a massive let-down. The mod is super super cool, but it's quite literally an idle game. Hell, to make the weak fusion plant, you need 57 zysc-baach sheets, each of which take 16 scandium ingots, which 14592 scandium. Which is 7296 runs in the fission multiblock. Each of which takes a few seconds. And that's not even close to the entire craft! Not to mention, everything in alchemistry is ridiculously cheap in comparison to draconic cores in the previous chapter. It's just queue up a recipe and come back 5 hours later. Over and over. Proposed change: **Less chemical per ingot. Maybe 8 from 16?**. If you can change the speed of the fission multiblock in the config, that would be best, but I assume that isn't possible.

The weak fusion multiblock is a mess. Each craft takes exactly one minute, and each Highly-Radioactive Dimension-Splitting Compound takes 1000 mb uranium and 360mb bromine, equivalent to 10 fusion crafts. Each stabilized dimensional machine frame is 8 of these, so effectively you're waiting at least an hour and a half per machine frame. HUH? (I also ignored that bromine comes from ytterbium, yet another fusion craft). I didn't play a few hundred hours of this pack to do the late-game equivalent of waiting for steel from a crude blast furnace again, but worse. **Please drastically increase the speed of this machine. Because at this point in the pack you have an extreme reactor generating tens of millions of rf/t power is not a concern. Don't waste more people's time.**

I also think it's a bit weird that the expensive part of fusion is the fission coolant unit and not the chemicals themselves, because the fission unit needs Cadmium-Arsenic compounds, which from arsenic (rainbow tablets), and cadmium (flying ointment). This isn't a complaint, just something I found a bit weird.

Lastly, also alchemistry, chaos shards feel a bit too expensive. Even doubling the output from 6 to 12 tiny chaos fragments would be massive. It's really just because this is incredibly difficult to automate as the numbers/ratios between all three liquicrafters are horrendous, and beam cores are particularly tricky to mass produce. **Solution: Increase yield of chaos shards, or change nickel chloride to a different chemical (or make beam cores yield much more nickel chloride)**

-------------------

**In general, I am very impressed in terms of balance in this pack, even this far in. But this pack feels silly when a lot of it is waiting on very, very slow machines that are too expensive, or too time consuming to scale up. Please don't make this an idle RPG!**

**Comment by KleinGrrmpf** [comment]
Disclaimer:
I have not yet played this far.
But looking at the recipes in question, I do get what you are saying. So I have some suggestions on implementing the suggestions that you gave:

As an addition to the machine speed, you could change it so that the machines are faster but also take more RF/t so that people are more likely to make the Draconic Reactor (if that is not yet the case). 
For the Modular Machines, there is another option/suggestion on how to make them faster but a little more balanced then too. Modular Machinery gives you the option to make machines upgradable. This was done with the Centrifuge in CJ for example (if you want a code reference Atri). You could make it that at first you would have to use the current version of the modular machine(s) in question but have the ability to upgrade them to work faster at a later time. This would not make them faster instantly but progressively as you need the machine(s) more and more.
Even from the slowness of the progress bar in JEI I can see that the Electricium and Skyfather Ingots take a long time. If you don't want to make seeds for those ingots, I would suggest yet another Modular Machine (something like a Tesla Coil Lightning Infuser or so) that can just make those Ingots at a faster pace after you have progressed in LightningCraft (implementing an upgrade system here might not be a bad idea either, depending on how you want to balance it).

Also, there are config options for the Fission and Fusion Multiblocks to change their processing tick time, so changing them is possible. Again, I would suggest making them take more energy too.

**Comment by 1234abcdcba4321** [comment]
I don't think Electricium needs a speed buff, mostly because you can just make blocks at a time and it actually gives you enough that you're only waiting on the other ingredients. Skyfather seeds would be appreciated, though.
There's still the option of just making more lightning tables to speed it up. (The important thing is to make sure you start producing the item before you need it, but skyfather is something you need enough of that running one machine constantly isn't actually enough. The pack constantly expects making multiple machines; hellfire forges and alchemy tables? They're slow, make more. Lightning infusers are slow? Just another one (and probably also increase LE production).
I don't see how "it's too cheap" and "it's too slow" can be your complaint at the same time unless the machine just flat-out isn't automatable, since if it's too slow AND too cheap you can just make a few more copies of the machines and then it's no longer cheap and also no longer slow.

**Comment by jehlp** [comment]
Honestly, while lightningcraft is annoying, it is manageable. We aren't particularly bottlenecked by it. Alchemistry on the other hand makes ever lightningcraft machine feel like an enhanced alloy smelter with a stellar capacitor
