### ISSUE TITLE
Intermedium infusion crystal auto infusion matrix bug

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/Divine-Journey-2#487]
**Modpack version:**
2.8.0

**Description:**
When crafting the intermedium infusion crystal (orange one) in the auto infusion matrix the input crystal stays in the input after crafting

**Comment by JohanniklasLp** [comment]
This is intended. It removes one durability from the crystal (Or rather it would, if they didn't have unlimited durability, which they have since 2.8).
You will see the same behaviour with the other infusion crystal crafts.

**Comment by Atricos** [comment]
"Intended" is a stretch, but this is how it works. Normally it would remove one durability point, but the input Crystal was made ubreakable, so it just stays in the Input Hatch.

The same was the case for the Bewitchment brews, they would leave an Empty Jar behind, which is why I had to add several custom items that are the combination of these brews, specifically for the Auto Infusion Matrix.

Point is, the only reasonable way I could see this being "fixed", is to add a custom item that the Infusion Crystal crafts into, and use that in the Auto Infusion Matrix for the upgrade. However since this upgrade doesn't have to be done too many times, I think that's unnecessary.

Buuut, you may try to convince me otherwise. :)
