### ISSUE TITLE
Inventory not updating unless Epic Backpack is open after moving save to later update

### ISSUE THREAD

**Issue by PopeMacatron** [Divine-Journey-2/Divine-Journey-2#511]
**Modpack version:**
2.8.0 and 2.7.0 (ones I tried it on)

**Description:**
This should be done after moving a save on a 2.5.0 profile to a 2.8.0 or 2.7.0 profile with two epic backpacks, one called Epic Backpack (default) and Epic Backpack 2 (just the default with a 2 at the end via an anvil) with different items in them.
After a bit of time playing items moved around in the inventory or picked up don't appear in the inventory or the new or expected positions, but they do when the epic backpack is open and when moved whilst it is open they stay in the new positions.

**Steps to reproduce:**
1.Create a 2.5.0 save, make the two Epic Backpacks and rename one to Epic Backpack 2, and just throw some random stuff in them.
2. Move the save over to a different profile that is in 2.8.0 or 2.7.0 with you old save still on a 2.5.0 profile
![Screenshot 2021-10-23 161052](https://user-images.githubusercontent.com/93043726/138561915-c06dfc70-386a-4527-9bd7-3818dee7c0cc.png)
![Screenshot 2021-10-23 161130](https://user-images.githubusercontent.com/93043726/138561942-326d17a5-2187-4445-8229-19a8d72b140f.png)
![Screenshot 2021-10-23 160838](https://user-images.githubusercontent.com/93043726/138561836-54005900-fe6e-49a4-99eb-b99a89bea934.png)
3. Open the game and play for ~ 2-3 minutes
4. Items moved around in inv or picked up no longer appear unless/until the epic backpack is open.

**Expected behaviour:**
Was just looking to update my save but accidentally said to make a new profiles, so I just move my world over (accidentally cut instead of copy and paste for making sure it was repeatable) but then this bug happened.
For instance I swap my pickaxe for a different one through drag a drop **without** the epic backpack open and exit out of my inventory the moved item disappears but mostly reappears on a reload or opening the Epic Backpack.
Or picking up an item off the ground, you hear the pickup and is disappears off the ground, but doesn't visually appear in your inventory until you reload or open the Epic Backpack

**Additional context:**
I assume it is probably a problem with having the save on an old version and then just shifting it onto a new save but it is weird how it breaks down though this rather than just not working or something else. This has made me  a bit concerned to I will stay on my old 2.5.0 save and not update it for a bit.
I can grab screen shots of the glitch happening but it takes like 5 mins for the modpack to load and I hate having to do it a again and again and it is literally just not updating the inv unless the epic backpack is open.
I check on a completely new creative save

**Comment by WaitingIdly** [comment]
this is an inventory desync - the inventory the client says the player has and the server says the player has are different.
this can be caused by a few factors, one of which being lag, another being a bug with roots wherein attempting to open the spellbook (keybind) without a staff causes a desync.
this can be observed by moving any item in your inventory around, and then opening an external inventory (such as the backpack, but a chest or crafting table also works) - which is when the client gets updated by the server.
once this starts, the only fix is leaving and rejoining the world.

you've probably already resolved this by now, but if you havent, i hope this helps. sorry for this slipping through and me only responding now.
