### ISSUE TITLE
A fatal error has occurred, this connection is terminated 1.12.2 Divine Journey 2

### ISSUE THREAD

**Issue by TheWeathersMan** [Divine-Journey-2/Divine-Journey-2#680]
### Modpack version

Divine Journey 2 - 2.14.2

### Java version

16.0.2

### RAM Allocated

8GBs

### Description

I am having a problem getting on my friends server. I have tried so many things, and nothing works. I understand why its not working. I was playing one day perfectly fine, and then I randomly got disconnected from the server, and now I cant get back on. I could really use some help. I dont specifically know what logs are needed, but if you need more information let me know.

### When did the crash happen?

Every time I try to join the server

### Steps to reproduce

Every time I try to join the server

### Minecraft crash report

https://mclo.gs/N9mUU72

**Comment by Preta-Crowz** [comment]
Completely invalid.
1. You should say modpack's "version". Not name.
2. Java version is not Minecraft version.
3. Crash report should be uploaded as file or site like pastebin.

**Comment by TheWeathersMan** [comment]
Sorry, I have never submitted anything on these forums before.
Modpack Version: Divine Journey 2 - 2.14.2
Java Version: java version "16.0.2"
Crash Report: https://mclo.gs/N9mUU72

**Comment by WaitingIdly** [comment]
looking in your crash report, you are actually using java 1.8.0_51. this is good, because you cannot run minecraft 1.12 with a java higher than java 1.8.

so, minecraft players have a limit to how much nbt data they can load. this looks like a classic "going over the limit". ask your server owner to reset your inventory, and youll be able to join the server again.
the most common reasons for this issue are having a full ae2 drive in inventory or finding a way to nest backpacks.

**Comment by TheWeathersMan** [comment]
You are amazing, I dont who you are, I dont know where you came from, but I love you!

**Comment by WaitingIdly** [comment]
i think its safe to assume that means the solution was found
