### ISSUE TITLE
Adding AIOT Botania to the modpack

### ISSUE THREAD

**Issue by Revemohl** [Divine-Journey-2/Divine-Journey-2#731]
### Mod Name

AIOT Botania, https://www.curseforge.com/minecraft/mc-mods/aiot-botania

### Reasons why this should be added

Multi-use tool progression feels a bit off in my opinion, basically the only thing you have after Actually Additions' AIOTs way early on and AA's drills a ways into the tech block is the Atomic Disassembler from Mekanism, at the end of the Botania chapter, and it can't even be enchanted for additional usefulness. These Botania AIOTs might be a decent way to bridge the gap while still offering enchantments, which means they could stay useful for a long time into the pack as well. (Words from someone who's still sticking to an emeradic AIOT early into the first Thaumcraft block)

### Additional context

Maybe adding a few more tools might take away from Tinkers' Construct, but that mod doesn't offer multi-use tools other than mattocks which only really work on dirt in addition to wood so I feel like this suggestion is relevant enough. There's also the Primal Crusher from Thaumcraft, but that's deep into its progression line and has the added bonus of repairing itself for free so I'd say that's also enough of a progression from these Botania ones. Lastly, maybe this addition won't remove the Disassembler's usefulness either because it can (nearly?) instantly break blocks and I'm not sure how much of a difference of speed it has in regards to the AIOTs - and you can always add a bit of balancing by giving the Botania AIOTs a reduced mining level in comparison to them as well.

**Comment by KleinGrrmpf** [comment]
If you want to change tools earlier in the Tech Block, there are the Dark Pick and Axe and the End Pick and Axe from EnderIO. Sure, they are not truly all-in-one, but with the right upgrades, the Pick works as Shovel too and the Axe doubles as a hoe. So they only use one more slot, they are enchantable and upgradable and can also insta-mine stone and dirt and the like with upgrades and enchantments.

**Comment by WaitingIdly** [comment]
a few thoughts:
- in addition to the already listed options, theres also the Erebus Jade Paxel (7), the Infinity Drill (13), and to some extent, Tinker's Construct's Crumbling trait (it works on some materials)
- since this is post-manual mining, the lack of enchanments do not matter (provided the tool is unbreakable, which the Mekanism Atomic Disassembler is)
- Botania AIOTs would mainly be duplicates of the already existing AA AIOTs

with these points in mind, i do not believe that adding this mod will improve players experience of the pack. you are free to do so, obviously - and i encourage it, since you want it - but i think the content added would be predominantly superfluous.

thank you for the suggestion!
