### ISSUE TITLE
Improve way of making energy

### ISSUE THREAD

**Issue by MrReps** [Divine-Journey-2/Divine-Journey-2#742]
### Mod Name

Advanced Generator

### Reasons why this should be added

Hi, 
I'm thinking that the pack as no way to produce energy in mid game except by making several solar panels thats are no fun to play with or by making lot of diesel generator. 

I mean there is other way to produce energy like ender io or thermal but they are both very unificient and very expensive for what they produce. 

I think a mod to produce energy like Advanced generator is a good mid game way of making power as an alternative of solar panel. Some blocs could be disabled or nerfed if you find it to much (i'm thinking of the heat exchanger wich is a maybe a to easy way of making steam.)

Thanks to have read me.

**Comment by KleinGrrmpf** [comment]
Diesel is very early game. People use solars and/or Rainbow Generator. The devs said they didn't want power to be a problem in the pack and thus didn't want to make it more complicated or give it more steps. Once you are past the Diesel Gen, you are fine.

**Comment by WaitingIdly** [comment]
a few thoughts:
- the problem of "solars are best, also boring" is best solved via buffing existing, but unused, options, rather than adding a new mod. 
- solars are a completely optional way of power generation:
  - upscale power storage (only viable on servers)
  - add more diesel gens (and make them run full-time)
  - use a few "inefficient" single-block thermal gen which are equal to a diesel gen in terms of fuel efficiency *before* upgrades
- in terms of functionality, it would basically just be a slightly-better diesel gen - you would have to supply it the same fuel - just more throughput of fluid->power and slightly more efficient conversion. 

for these reasons, i will not be adding Advanced Generators to the pack. thank you for your suggestion.

**Comment by MrReps** [comment]
thanks for your answer !
