### ISSUE TITLE
osgloglas essence recipe 

### ISSUE THREAD

**Issue by JetMage28** [Divine-Journey-2/Divine-Journey-2#821]
### Describe the feature

osgloglas is a heavily used ingot as soon as you get it, and all throughout the pack. in the enderIO alloy smelter it costs 20,000 rf per ingot. osglolapis (a common consumer, going up the chain to mobgrindium blocks for void reagent) costs 4,000 rf per craft. osgloglas is consumed at a faster rate than it can reasonably be produced. i believe that one way to solve this would be to add a recipe for osgloglas using the mystical agriculture essences of the ingredients. for example, 3 of each refined glowstone, refined obsidian, and osmium essence to make 1-3 osgloglas ingots at the devs' discretion. 

### Reasons why this should be added

there are too many uses for osgloglas and it's crafting chain(s), be it the aforementioned mobgrindium, to being heavily used in most energy storage items. it is consumed at too high of a rate to be kept as slow as it is. 

### Describe alternatives you've considered

if the above recipe is too cheap, one alternative could be to add a mass/multi alloying multiblock for extremely heavily used alloys like osgloglas. another could simply be adding an alloying recipe for osgloglas blocks. 

### Your Divine Journey 2 Discord Username

G-force#8488

**Comment by WaitingIdly** [comment]
i dont think this is needed. being limited by osgloglas production post-MA is a sign that you should increase throughput. 

additionally, if we add a recipe for osgloglas, whats the logic behind *not* adding one for osglolapis? or the material after that? etc? i view expanding essence use in such a way to be a slippery slope.
currently, essence use is limited to:
- direct product
- some ore blocks
- a few unique ingredients that are otherwise hard/impossible/laggy to automate (eg coquina, aerogel, demon ingots)
as osgloglas is a simple alloy, it doesnt fit any of these types.
