### ISSUE TITLE
Raw Mouse Input

### ISSUE THREAD

**Issue by ZHAY10086** [Divine-Journey-2/Divine-Journey-2#897]
### Mod Name

https://www.curseforge.com/minecraft/mc-mods/raw-input-1-12-2

### Reasons why this should be added

It fixes the annoying mouse jittering issue.
Also, prevent unexpected view change when switching windows (with `F3 + P ` disabled).

### Your Divine Journey 2 Discord Username

ZY#4401

**Comment by WaitingIdly** [comment]
what issue are you talking about. elaborate

**Comment by ZHAY10086** [comment]
> what issue are you talking about. elaborate

Should I repeat the issue again here?

**Comment by mantikafasi** [comment]
as someone who is experiencing this,%99 of the time rotating mouse is very inconsistent (sometimes it turns 360 degree and sometimes 90 with same movement) this mod fixes that issue

**Comment by Atricos** [comment]
Personally I have never encountered this issue, but I don't doubt it exists.

However it seems whether or not the mod fixes the issue depends on the hardware or mouse driver (see here: https://github.com/seanld03/RawInputMod-1.12.2-1.7.10/issues/2 - it seems in some cases adding the mod made things worse).

However since this mod only changes the inputs of the game, it should just be a client-only mod, so you can feel free to add it to your own mods folder, and still be able to join DJ2 servers.
